
# Business Data Analytics - Practice Session_01 - 2025/2026

## Introduction to Python

## University of Tartu

1. **Python Introduction**
2. **Pandas tutorial**
3. **Slicing and dicing data**

In [13]:
# print("Welcome to HELL")
s = "Welcome to HELL"
print(s)
s = 59
print(f"My age is {s} \nBut I will reverse it soon to {s/2}")

Welcome to HELL
My age is 59
But I will reverse it soon to 29.5

<div class="alert alert-block alert-success">

# Introduction to Python:

1. **High level programming language**,
2. **Dynamic typing:** any type checking is happen during the run time instead of compile time.
3. **Interpreted language** (live coding) it could be slower than **compiled** code
4. Started since 1991, **Python 2:** 2000, **Python 3:** 2008, **Anaconda:** 1999
</div>

<div class="alert alert-block alert-success">


# What makes Python different or Why Python?:
1. Yes, It's suitable for kids 😉, but it's also growing very fast.
2. According to [PYPL](http://pypl.github.io/PYPL.html) (PopularitY of Programming Language), Python has ranked the **first programming language worldwide.** With a 4% growth rate. Also from [IEEE spectrum](https://spectrum.ieee.org/computing/software/the-top-programming-languages-2019) report. [Most Popular Programming Languages 1965 - 2019](https://www.youtube.com/watch?v=Og847HVwRSI)
3. Python philosophy `PEP 20- the Zen of Python` [pep-0020](https://www.python.org/dev/peps/pep-0020/)


# Python basics:
1. You can find a very good tutorial about Python on [DataCamp](https://www.datacamp.com/) or [learnpython](https://www.learnpython.org/)
2. You can also check [official website](https://wiki.python.org/moin/BeginnersGuide). They have lots of information there.
    
    
# Where to write Python code?:  
1. Python command `REPL` (Read - Eval - Print - Loop), Interactive development
2. `Ipython`: Robust interactive shell.
3. `IDE` (Integrated development environment ) such as [Pycharm](https://www.jetbrains.com/pycharm/), or [Anaconda](https://www.anaconda.com/), [Anaconda_installation](https://docs.anaconda.com/anaconda/install/)
4. Any text editor: `Notepad`, `Vim`, `Atom`
5. You can use it online with [`google colab`](https://colab.research.google.com/notebooks/welcome.ipynb)
</div>

# Python Basics:
1. Data types.
2. Basic Operators
3. String Formatting
4. Conditions
5. Loops
6. Functions
7. Dictionaries

### 1. Data types:

1. We have many different data types in any programming language, such as `Integer`, `float`, `complex`, `boolean`, `String`, `Lists`, and `Tuple`.

2. Python is completely `object-oriented`, and not `statically typed`. You do not need to declare variables before using them or declare their type. **Every variable in Python is an `object.`**

3. In python we don't need to declare the types of the data before using it:
    * **Python Integer:**    `x = 5`
    * **Java Integer:**     `int x = 5`;
    
    
    
4. **How to declare a variable in Python?**
    * use the following standard form:    
    <center> <font color='green'> [variable name] [assignment operator] [value]</font></center>
    <font color='red'> Ex: </font>
    <center> <font color='black'> myVar = myValue </font></center>
    <center> <font color='black'> x = 6 </font></center>

In [19]:
# Integer
%%time
x = 5
y = 6.1
print(f"sum of two integers is: {x+y}\n")

sum of two integers is: 11.1

CPU times: user 926 µs, sys: 111 µs, total: 1.04 ms
Wall time: 2.55 ms

In [ ]:
# Float/Double
x = 5.1 # float
y = 6   # int
print(f"sum of float and int: {x+y}\n")

sum of float and int: 11.1

In [26]:
# Boolean:
x = True
y = False

if x:
    print("X is True\n")
elif not x:
    print("X is False\n")
elif y or x:
    print("Unknown")

X is True

# this is markdown

In [ ]:
a = 4
b =  4

In [27]:
# Strings:
x = "Hello my string"
y = "Welcome to BDA's course"
print(f"my x string is: {x}\n")
print(f"my y string is: {y}\n")

my x string is: Hello my string

my y string is: Welcome to BDA's course

In [28]:
# @title Default title text
# Lists:
myList1=[1,2,3,4]
myList2=[10, "BDA", 1.2, True]

print(f"my first list is: {myList1}")
print(f"my second list is: {myList2}\n")

my first list is: [1, 2, 3, 4]
my second list is: [10, 'BDA', 1.2, True]

In [36]:
myList1=[1,2,3,4]
myList1.append(5)
# myList1.pop(0)
myList1

[1, 2, 3, 4, 5]

In [39]:
# [myList1] + [myList2]

In [47]:
new_list = [i**2 for i in myList1]
new_list

[1, 4, 9, 16, 25]

In [ ]:
# Tuples:
myTuple1=(1,2,3,4)
myTuple2=(10, "BDA", 1.2, True)

print(f"my first tuple is: {myTuple1}")
print(f"my second tuple is: {myTuple2}")

my first tuple is: (1, 2, 3, 4)
my second tuple is: (10, 'BDA', 1.2, True)

### 2. Basic Operators:

2.1. **Arithmetic Operators:** Just as any other programming language, the `addition`, `subtraction`, `multiplication`, and `division` operators can be used with numbers.

In [51]:
# numbers
mysum = 1 + 2.2  # addition
mymul = 2 * 3  # multiplication
mydivision = 6.4 / 3 # division

print("Addition is: ", mysum)
print("Multiplication is: ", mymul)
print("Division is: ", mydivision,'\n')

Addition is:  3.2
Multiplication is:  6
Division is:  2.1333333333333333

In [54]:
# strings
mystring1 = " Welcome to"
mystring2 = " BDA course"
mystring = mystring1 + mystring2
print("Addition is: ", mystring)
print("Multiplication is: ", mystring1 *2)
# print("Division is: ", mystring1 /2,'\n')

Addition is:   Welcome to BDA course
Multiplication is:   Welcome to Welcome to

In [ ]:
# Lists
even_numbers = [2,4,6,8]
odd_numbers = [1,3,5,7]

addition = odd_numbers + even_numbers
print(f"\naddition of two lists is: {addition}")

# Just as in strings,
# Python supports forming new lists with a repeating sequence using the multiplication operator:
print(f"\nmultiplication of two lists is: {even_numbers* 2}" )

addition of two lists is: [1, 3, 5, 7, 2, 4, 6, 8]

multiplication of two lists is: [2, 4, 6, 8, 2, 4, 6, 8]

In [57]:
# Try to predict what the answer will be. Does python follow the order of operations?
number = 1 + 2 * 2.9 // 2.0
print(number)

3.0

In [58]:
# Another operator available is the (modulus) modulo $(%)$ operator,
# which returns the integer remainder of the division. dividend % divisor = remainder.

remainder = 11 % 3
print(f" the remainder is: {remainder}")

# Using two multiplication symbols makes a power relationship.
squared = 7 ** 2
cubic = 2 ** 3
print(f" the squared is: {squared}")
print(f" the cubic is: {cubic}")

 the remainder is: 2
 the squared is: 49
 the cubic is: 8

### 3. String Formatting:
1. Python uses `C-style` string formatting to create new, formatted strings. The `"%"` operator is used to format a set of variables enclosed in a **" tuple"** (a fixed-size list), together with a format string, which contains normal text together with "argument specifiers", special symbols like `"%s"` and `"%d"`.

2. we can use `format()`

In [60]:
# Let's say you have a variable called "name" with your user name in it,
# and you would then like to print(out a greeting to that user.)

# This prints out "Hello, John!"
name = "John"
age = 23
print(f"Hello, {name}")

Hello, John

In [63]:
# To use two or more argument specifiers, use a tuple (parentheses):
# This prints out "John is 23 years old."
name = "John"
age = 23
print("%s is %d years old." % (name, age))

John is 23 years old.

In [ ]:
# using format() starting from python3.6
print("Using format()")
print(f"{name} is {age} years old")

Using format()
John is 23 years old

In [ ]:
# using string concatenation
print("Using string concatenation")
print(name + "is " + str(age) + " years old")

Using string concatenation
Johnis 23 years old

# Ex: 1

1. You will need to write a format string that prints out the data using the following syntax: **Hello `John` `Doe`. Your current balance is `$53.44`.**

In [ ]:
# sol 1
fname = "John"
lname = "Doe"
balance = 53.44


## TODO
# print "Hello John Doe. Your current balance is $53.44."
print(f"Hello {fname} {lname}. Your current balance is {balance}$.")

Hello John Doe. Your current balance is $53.44.

### 4. Condition:

1. Python uses boolean variables to evaluate (`True`, and `False`) conditions. The boolean values True and False are returned when an expression is compared or evaluated. For example:

    * Notice that variable assignment is done using a single equals operator `"="`, whereas comparison between two variables is done using the double equals operator `"=="`. The "not equals" operator is marked as `"!="`.
    

2. **Boolean operators**
    
    * The `"and"`, `"or"`, `not`, and `in` boolean operators allow building complex boolean expressions, for example:

In [64]:
x = 2
print(x == 2)
print(x == 3)
print(x < 3)
print(x != 3)

True
False
True
True

In [70]:
# and & or
x =3
y =2

if x == 3 and y==2:
    print("X, and Y are True")
elif x==3  or y==1:
    print("X or Y is True")
else:
    print("X, and Y are false")

X, and Y are True
hello

# Note:
* Python uses `indentation` to define code blocks, instead of brackets. The standard Python indentation is `4 spaces`, although `tabs` and any other space size will work, as long as it is `consistent`. Notice that code blocks do not need any termination.

In [ ]:
# Code block for If stmt
statement = False
another_statement = True

if statement is True:
    # do something
    pass
elif another_statement is True: # else if
    # do something else
    pass
else:
    # do another thing
    pass

### 5. Loops:
1. There are two types of loops in Python, for and while:
    * For Loop
    * While Loop

In [71]:
# For
numbers = [2, 3, 5, 7]
for number in numbers:
    print(number)

2
3
5
7

In [ ]:
# For loops can iterate over a sequence of numbers using the `"range"` function.
# Note that the range function is `zero based.`

# Prints out the numbers 0,1,2,3,4
for x in range(5):
    print(x)

0
1
2
3
4

In [73]:
# Prints out 3,5,7
for x in range(3, 20, 3):
    print(x)

3
6
9
12
15
18

* While loop

In [75]:
# Prints out 0,1,2,3,4

count = 0
while count < 5:
    print(count)
    count +=  1  # This is the same as count = count + 1

0
1
2
3
4

* `"break"` and `"continue"` statements:

    1. `break` is used to exit a for loop or a while loop, whereas `continue` is used to skip the current block, and return to the "for" or "while" statement. A few examples:

In [77]:
# Prints out 0,1,2,3,4

count = 0
while True:
    print(count)
    count += 1
    if count >= 5:
        break

0
1
2
3
4

In [80]:
# Prints out only odd numbers - 1,3,5,7,9
for x in range(2, 10):
    # Check if x is even
    if x % 2 != 0:
      print(x)

3
5
7
9

In [ ]:
counter = 0
for i in range(100):
  counter += i
print(f" the sum of numbers is {counter}")

 the sum of numbers is 4950

# Ex 2:

1. Loop through and print out all even numbers from the numbers list in the same order they are received. Don't print any numbers that come after 237 in the sequence.

In [81]:
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]

# your code goes here
for number in numbers:
    if number == 237:
        break

    if number % 2 != 0:
        continue


    print(number)

402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918

### 6. Functions:

#### What are Functions?

Functions are a convenient way to divide your code into useful `blocks`, allowing us to `order` our code, make it more `readable`, `reuse` it and `save some time`. Also, functions are a key way to define `interfaces` so programmers can share their code.


#### How do you write functions in Python?

As we have seen in previous tutorials, Python makes use of `blocks`.
   * A `block` is an area of code of written in the format of:
   * Where a `block` line is more Python code (even another block), and the blockhead is of the following format: `block_keyword block_name(argument1,argument2, ...)` Block keywords you already know are `"if"`, `"for"`, and `"while"`.

* **Functions** in python are defined using the block keyword `"def"`, followed with the `function's name` as the `block's name`. For example:

In [82]:
def my_function():
    print("Hello From My Function!")

#### How do you call functions in Python?

* Simply write the` function's name followed by ()`, placing any required `arguments` within the brackets. For example, let's call the functions written above (in the previous example):

In [85]:
my_function()

Hello From My Function!

* Functions with parameters

In [104]:
# Functions may also receive arguments (variables passed from the caller to the function). For example:
def my_function_with_args(username, greeting=" teste "):
    mystring = "Hello, %s , From My Function, I wish you %s!"%(username, greeting)
    return mystring

In [105]:
out = my_function_with_args("BDA", "a great day")
print(out)

Hello, BDA , From My Function, I wish you a great day!

# Ex 3:
1. Create a function to add two numbers and return the addition, and multiplication

In [106]:
# TODO
# replace ? with your code
def myFunc(x, y):
    addition = x + y
    mul = x * y
    return addition, mul

a = 10
b = 9
addition, multiplication = myFunc(a, b)
print(f"my two numbers are {a}, and {b}")
print(f"the addition is: {addition}")
print(f"the multiplication is: {multiplication}")

my two numbers are 10, and 9
the addition is: 19
the multiplication is: 90

In [107]:
def square(x):
  y = x * x
  return y

square (10)
print(y)

2

### 7. Dictionaries:

* A `dictionary` is a data type similar to `arrays`, but works with **keys and values** instead of indexes. Each value stored in a dictionary can be accessed using a key, which is any type of object (a string, a number, a list, etc.) instead of using its index to address it.

* `For example`, a database of phone numbers could be stored using a dictionary like this:

Alice 1234576
Bob 6784584

In [110]:
# empty dict
phonebook = {}

#phonebook['Key'] = Value
phonebook["John"] = 938477566
phonebook["Jack"] = 938377264
phonebook["Jill"] = 947662781

# print(f"my dict is: {phonebook}\n")

for k,v in phonebook.items():
    print(f"key name is: {k}, and phone number value is: {v}")

key name is: John, and phone number value is: 938477566
key name is: Jack, and phone number value is: 938377264
key name is: Jill, and phone number value is: 947662781

In [114]:
# Alternatively, a dictionary can be initialized with the same values in the following notation:

phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}
print(phonebook)

# removing key and value

del phonebook["John"]

print(phonebook)

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781}
{'Jack': 938377264, 'Jill': 947662781}

## Pandas Tutorial:


## Why Pandas?

1. Let's learn some of the most important `pandas` features for:
    * exploring.
    * cleaning.
    * transforming
    * visualizing.
    * learning from data.


2. The pandas package is the most important tool of Data Scientists and Analysts working in Python today. Pandas is the backbone of most data projects.


3. `[pandas]` is derived from the term **panel data**, an econometrics term for data sets that include observations over multiple time periods for the same individuals. — Wikipedia.

4. In this session, we will go over the essential bits of information about pandas, including how to install it, its uses, and how it works with other common Python data analysis packages such as matplotlib and scikit-learn.


5. For example, say you want to explore a dataset stored in a CSV on your computer. Pandas will extract the data from that CSV into a DataFrame — a table, basically — then let you do things like:

    * Calculate statistics and answer questions about the data, like
        * What's the average, median, max, or min of each column?
        * Does column A correlate with column B?
        * What does the distribution of data in column C look like?
        
    * Clean the data by doing things like removing missing values and filtering rows or columns by some criteria
    * Visualize the data with help from `Matplotlib`. Plot bars, lines, histograms, bubbles, and more.
    * Store the cleaned, transformed data back into a CSV, other file or database

6. **Pandas** is built on top of the `NumPy` package, meaning a lot of the structure of NumPy is used or replicated in Pandas. Data in pandas is often used to feed statistical analysis in `SciPy`, plotting functions from `Matplotlib`, and machine learning algorithms in `Scikit-learn`.

## Pandas First Steps


### Install and import:

* Pandas is an easy package to install. Open up your terminal program (for Mac users) or command line (for PC users) and install it using either of the following commands:

`conda install pandas`

OR

`pip install pandas`

* Alternatively, if you're currently viewing this article in a Jupyter notebook you can run this cell:

`!pip install pandas`


* The `!` at the beginning runs cells as if they were in a terminal.


* To import pandas we usually import it with a shorter name since it's used so much:

In [121]:
# !pip install pandas
# !mkdir test
# !ls -la

In [122]:
import pandas as pd
pd?

## Core components of pandas: Series and DataFrames

1. The primary two components of pandas are the Series and DataFrame.

2. A **Series** is essentially a `column`, and a **DataFrame** is a `multi-dimensional table made up of a collection of Series`.

In [126]:
from IPython.display import Image
# Image(filename='pandas.png')
# source: https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/

1. `DataFrames` and `Series` are quite similar in that many operations that you can do with one you can do with the other, such as filling in null values and calculating the mean.


2. You'll see how these components work when we start working with data below.

### Creating DataFrames from scratch:


1. There are many ways to create a DataFrame from scratch, but a great option is to just use a simple **dict**.


* Let's say we have a fruit stand that sells apples and oranges. We want to have a column for each fruit and a row for each customer purchase. To organize this as a `dictionary` for pandas we could do something like:

In [138]:
import numpy as np
data = {
    'apples': [3, 2, 0, 1],
    'oranges': [0, 3, 7, 10]
}

And then pass it to the pandas `DataFrame` constructor:

In [ ]:
?pd.DataFrame

In [139]:
purchases = pd.DataFrame(data)

purchases

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1       10

### Imputation of Missing Values in Pandas

Missing values, often represented as `NaN` (Not a Number) in pandas, can negatively impact data analysis and machine learning models. Imputation is the process of replacing these missing values with substituted values.

First, let's confirm the missing values in our `df` DataFrame:

In [135]:
df = purchases
print("Missing values before imputation:")
display(df.isnull().sum())

Missing values before imputation:

apples     0
oranges    1
dtype: int64

From the output, we can see that the `name` and `price` columns have missing values. Here are some common imputation strategies:

1.  **Mean Imputation**: Replace missing values with the mean of the column. This is suitable for numerical data but can distort the distribution and relationships.
2.  **Median Imputation**: Replace missing values with the median of the column. This is more robust to outliers than mean imputation.
3.  **Mode Imputation**: Replace missing values with the most frequent value (mode) of the column. This is often used for categorical data or discrete numerical data.
4.  **Forward Fill (`ffill`)**: Propagate the last valid observation forward to next missing ones. Useful for time series data.
5.  **Backward Fill (`bfill`)**: Propagate the next valid observation backward to previous missing ones. Also useful for time series data.
6.  **Constant Value Imputation**: Replace missing values with a specific constant (e.g., 0, 'Unknown').
7.  **Dropping Rows/Columns**: If the number of missing values is small or the row/column is not critical, you might choose to drop them. (Note: Dropping rows with missing essential identifiers like 'name' was already demonstrated in a previous cell: `LHfovIlNVf5G`).

Let's demonstrate some of these on our `df`:

In [ ]:
# Original DataFrame for comparison
print("Original DataFrame with missing values:")
display(df)

# Median Imputation for 'price'
# This was already demonstrated in cell -aZXP3zwU5Cu. Let's re-run and explain it.
median_price = df["price"].median(skipna=True)
imputed_median_price_df = df.copy()
imputed_median_price_df["price"] = imputed_median_price_df["price"].fillna(median_price)
print("\nDataFrame after Median Imputation for 'price' (using value: ", median_price, "):")
display(imputed_median_price_df)

# Mean Imputation for 'price'
mean_price = df["price"].mean(skipna=True)
imputed_mean_price_df = df.copy()
imputed_mean_price_df["price"] = imputed_mean_price_df["price"].fillna(mean_price)
print("\nDataFrame after Mean Imputation for 'price' (using value: ", round(mean_price, 2), "):")
display(imputed_mean_price_df)

# Mode Imputation for 'name' (categorical data)
# Note: mode can return multiple values if there's a tie, so we take the first one.
mode_name = df["name"].mode()[0]
imputed_mode_name_df = df.copy()
imputed_mode_name_df["name"] = imputed_mode_name_df["name"].fillna(mode_name)
print("\nDataFrame after Mode Imputation for 'name' (using value: '", mode_name, "'):")
display(imputed_mode_name_df)

# Forward Fill (ffill) for 'price'
ffill_df = df.copy()
ffill_df["price"] = ffill_df["price"].ffill()
print("\nDataFrame after Forward Fill for 'price':")
display(ffill_df)

# Backward Fill (bfill) for 'price'
bfill_df = df.copy()
bfill_df["price"] = bfill_df["price"].bfill()
print("\nDataFrame after Backward Fill for 'price':")
display(bfill_df)

The choice of imputation strategy depends on the nature of your data and the specific problem you are trying to solve. For the `price` column, median or mean imputation are common choices, while for `name`, filling with a mode or a placeholder like 'Unknown' (as shown in cell `y5c3qeCNUfVf`) is more appropriate.

#### How did that work?

1. Each **(key, value)** item in data corresponds to a column in the resulting DataFrame.


2. The Index of this DataFrame was given to us on creation as the numbers 0-3, but we could also create our own when we initialize the DataFrame.


* Let's have customer names as our index:

In [141]:
purchases = pd.DataFrame(data, index=['June', 'Robert', 'Lily', 'David'])

purchases

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1       10

So now we could **loc**ate `"loc[]"` a customer's order by using their name:

In [145]:
purchases.loc['David'] # loc[index]

apples      1
oranges    10
Name: David, dtype: int64

* There's more on locating and extracting data from the DataFrame later, but now you should be able to create a DataFrame with any random data to learn on.

* Let's move on to some quick methods for creating DataFrames from various other sources.

Another way to locate an observation is by its index using `"iloc[]"`

In [146]:
purchases.iloc[2]

apples     0
oranges    7
Name: Lily, dtype: int64

## How to read in data

* It’s quite simple to load data from various file formats into a DataFrame. In the following examples we'll keep using our apples and oranges data, but this time it's coming from various files.

### Reading data from CSVs

* With CSV files all you need is a single line to load in the data:

In [151]:
purchases.to_csv("purchases.csv", index=True, sep=",") # here we created csv file
df = pd.read_csv('purchases.csv') # this line reads data from a csv file
df

  Unnamed: 0  apples  oranges
0       June       3        0
1     Robert       2        3
2       Lily       0        7
3      David       1       10

* CSVs **don't** have indexes like our DataFrames, so all we need to do is just designate the index_col when reading:

In [152]:
df = pd.read_csv('purchases.csv')#, index_col=0)

df

  Unnamed: 0  apples  oranges
0       June       3        0
1     Robert       2        3
2       Lily       0        7
3      David       1       10

* Here we're setting the index to be column **zero**.


* You'll find that most CSVs won't ever have an index column and so usually you don't have to worry about this step.

### Reading data from JSON

* If you have a JSON file — which is essentially a stored Python dict — pandas can read this just as easily:

In [ ]:
purchases.to_json("new.json")

In [ ]:
df = pd.read_json('new.json')

df

        apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

* Notice this time our index came with us correctly since using JSON allowed indexes to work through nesting. Feel free to open `data_file.json` in a notepad so you can see how it works.

# Ex 4:

1. Create random dataFrame using `dict`.
2. save this random data as `csv`, and `json` file.
3. read the saved `csv file` again, and set the index col.
4. use `iloc` to get the second row from your dataFrame.

In [ ]:
# # TO DO
# # create dict
your_dict = {
    'Name': ['Jhon', 'Ann'],
    'City': ['Tartu', 'Tallin']
}

# # save df as csv and json
df = pd.DataFrame(your_dict, index=['row1', 'row2'])
df.to_csv('./df.csv')
df.to_json('./df.json')

# # read the csv file
read_df = pd.read_csv('./df.csv')

# # get the second row
read_df.iloc[1]

Unnamed: 0      row2
Name             Ann
City          Tallin
Name: 1, dtype: object

# Data Exploration

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [156]:
movies_df = pd.read_csv('/content/IMDB-Movie-Data.csv')
movies_df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [157]:
# import pandas as pd

# movies_df = pd.read_csv('/content/IMDB-Movie-Data (1).csv')
# movies_df.head()

In [ ]:
# read csv file
import pandas as pd

movies_df = pd.read_csv("/content/imdb_top_1000.csv")

movies_df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

* We're loading this dataset from a CSV and designating the movie titles to be our index.

### Viewing your data

* The first thing to do when opening a new dataset is print out a few rows to keep as a visual reference. We accomplish this with `.head()`:

In [160]:
movies_df.head(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0

* `.head()` outputs the first five rows of your DataFrame by default, but we could also pass a number as well: `movies_df.head(10)` would output the top ten rows, for example.


* To see the last five rows use `.tail()`. tail() also accepts a number, and in this case we printing the bottom two rows.:

In [161]:
movies_df.tail(3)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

* Typically when we load in a dataset, we like to view the first five or so rows to see what's under the hood. Here we can see the names of each column, the index, and examples of values in each row.

* You'll notice that the index in our DataFrame is the Title column, which you can tell by how the word Title is slightly lower than the rest of the columns.

## 2. Data Understanding

### Getting info about your data

* `.info()` should be one of the very first commands you run after loading your data:

In [162]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

* `.info()` provides the essential details about your dataset, such as the number of rows and columns, the number of non-null values, what type of data is in each column, and how much memory your DataFrame is using.


* Notice in our movies dataset we have some obvious missing values in the Revenue and Metascore columns. We'll look at how to handle those in a bit.


* Another fast and useful attribute is `.shape`, which outputs just a tuple of (rows, columns):

In [163]:
movies_df.shape
# there are 1000 rows and 11 columns in the dataset

(1000, 12)

* Let's see what are the columns in the dataframe

In [164]:
movies_df.columns
# Pandas DataFrame.columns attribute return the column labels of the given Dataframe.

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

* column.values method returs an array of index

In [165]:
movies_df.columns.values

array(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes',
       'Revenue (Millions)', 'Metascore'], dtype=object)

* Iterating the columns

In [166]:
for col in movies_df.columns:
    print(col)

Rank
Title
Genre
Description
Director
Actors
Year
Runtime (Minutes)
Rating
Votes
Revenue (Millions)
Metascore

### Understanding your variables

* Using **describe()** on an entire DataFrame we can get a summary of the distribution of continuous variables:

In [167]:
movies_df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

* Understanding which numbers are continuous also comes in handy when thinking about the type of plot to use to represent your data visually.

* .describe() can also be used on a **categorical variable** to get the count of rows, unique count of categories, top category, and freq of top category:

In [ ]:
movies_df['Genre'].describe()

count                        1000
unique                        207
top       Action,Adventure,Sci-Fi
freq                           50
Name: Genre, dtype: object

In [174]:
movies_df.Genre.value_counts()[-10:] # Series

Genre
Adventure,Biography          1
Adventure,Biography,Crime    1
Comedy,Drama,Musical         1
Comedy,Family,Romance        1
Biography,Drama,Family       1
Drama,Fantasy,Musical        1
Adventure,Family             1
Adventure,Comedy,Fantasy     1
Drama,Family,Music           1
Comedy,Family,Fantasy        1
Name: count, dtype: int64

In [175]:
movies_df['Genre'].unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [ ]:
pd.unique(movies_df['Genre'])

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

## DataFrame slicing, selecting, extracting

* Up until now we've focused on some basic summaries of our data. We've learned about simple column extraction using single brackets, and we imputed null values in a column using fillna(). Below are the other methods of slicing, selecting, and extracting you'll need to use constantly.

* It's important to note that, although many methods are the same, DataFrames and Series have different attributes, so you'll need be sure to know which type you are working with or else you will receive attribute errors.

* Let's look at working with columns first.

#### By column

* You already saw how to extract a column using square brackets like this:

In [ ]:
genre_col = movies_df['Genre']

type(genre_col)

pandas.core.series.Series

* This will return a **Series**. To extract a column as a DataFrame, you need to pass a list of column names. In our case that's just a single column:

In [ ]:
genre_col = movies_df[['Genre']]

type(genre_col)

pandas.core.frame.DataFrame

* Since it's just a list, adding another column name is easy:

In [ ]:
subset = movies_df[['Genre', 'Rating']]

subset.head()

                      Genre  Rating
0   Action,Adventure,Sci-Fi     8.1
1  Adventure,Mystery,Sci-Fi     7.0
2           Horror,Thriller     7.3
3   Animation,Comedy,Family     7.2
4  Action,Adventure,Fantasy     6.2

#### Conditional selections

* We’ve gone over how to select columns and rows, but what if we want to make a conditional selection?


* For example, what if we want to filter our movies DataFrame to show only films directed by Ridley Scott or films with a rating greater than or equal to 8.0?


* To do that, we take a column from the DataFrame and apply a Boolean condition to it. Here's an example of a Boolean condition:

In [ ]:
condition = (movies_df['Director'] == "Ridley Scott")

condition.head()

0    False
1     True
2    False
3    False
4    False
Name: Director, dtype: bool

* We want to filter out all movies not directed by Ridley Scott, in other words, we don’t want the False films. To return the rows where that condition is True we have to pass this operation into the DataFrame:

In [ ]:
movies_df['Director'].unique()

In [182]:
# movies_df[condition]
# OR
movies_df[(movies_df['Director'] == "Ridley Scott") & (movies_df["Rating"] > 7.5)]
# movies_df[movies_df.Director == 'Ridley Scott']

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
102,103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
470,471,American Gangster,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0

* You can get used to looking at these conditionals by reading it like: **Select movies_df where movies_df director equals Ridley Scott.**


* Let's look at conditional selections using numerical values by filtering the DataFrame by ratings:

In [183]:
movies_df[movies_df.Rating >= 8.6].head(3)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0

* We can make some richer conditionals by using logical operators **| for "or" and & for "and"**.

* Let's filter the the DataFrame to show only movies by Christopher Nolan OR Ridley Scott:

In [184]:
movies_df[(movies_df['Director'] == 'Christopher Nolan') | (movies_df['Director'] == 'Ridley Scott')].head(15)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
64,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
102,103,The Martian,"Adventure,Drama,Sci-Fi",An astronaut becomes stranded on Mars after hi...,Ridley Scott,"Matt Damon, Jessica Chastain, Kristen Wiig, Ka...",2015,144,8.0,556097,228.43,80.0
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
387,388,Robin Hood,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0
470,471,American Gangster,"Biography,Crime,Drama","In 1970s America, a detective works to bring d...",Ridley Scott,"Denzel Washington, Russell Crowe, Chiwetel Eji...",2007,157,7.8,337835,130.13,76.0
516,517,Exodus: Gods and Kings,"Action,Adventure,Drama",The defiant leader Moses rises up against the ...,Ridley Scott,"Christian Bale, Joel Edgerton, Ben Kingsley, S...",2014,150,6.0,137299,65.01,52.0
521,522,The Counselor,"Crime,Drama,Thriller",A lawyer finds himself in over his head when h...,Ridley Scott,"Michael Fassbender, Penélope Cruz, Cameron Dia...",2013,117,5.3,84927,16.97,48.0
530,531,A Good Year,"Comedy,Drama,Romance",A British investment broker inherits his uncle...,Ridley Scott,"Russell Crowe, Abbie Cornish, Albert Finney, M...",2006,117,6.9,74674,7.46,47.0
737,738,Body of Lies,"Action,Drama,Romance",A CIA agent on the ground in Jordan hunts down...,Ridley Scott,"Leonardo DiCaprio, Russell Crowe, Mark Strong,...",2008,128,7.1,182305,39.38,57.0

In [ ]:
movies_df[(movies_df['Director'] == 'Christopher Nolan') & (movies_df['Rating'] >= 6)].head(15)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Interstellar,37,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
The Dark Knight,55,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
The Prestige,65,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
Inception,81,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
The Dark Knight Rises,125,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0

# Advanced data manipulations

In [185]:
import pandas as pd
import numpy as np
from datetime import datetime

In [186]:
data = [
    {"id": 1, "name": "Apple",   "category": "Fruit",     "price": 1.20, "quantity": 10, "city": "Lisbon",  "date": "2025-08-01"},
    {"id": 2, "name": "Banana",  "category": "Fruit",     "price": 0.80, "quantity": 25, "city": "Porto",   "date": "2025-08-02"},
    {"id": 3, "name": "Orange",  "category": "Fruit",     "price": 1.00, "quantity": 15, "city": "Porto",   "date": "2025-08-03"},
    {"id": 4, "name": "Tomato",  "category": "Vegetable", "price": 2.50, "quantity": 12, "city": "Lisbon",  "date": "2025-08-04"},
    {"id": 5, "name": "Cucumber","category": "Vegetable", "price": 2.10, "quantity":  8, "city": "Coimbra", "date": "2025-08-05"},
    {"id": 6, "name": "Apple",   "category": "Fruit",     "price": 1.20, "quantity": 10, "city": "Lisbon",  "date": "2025-08-01"}, # duplicate
    {"id": 7, "name": None,      "category": "Fruit",     "price": np.nan, "quantity": 5, "city": "Faro",   "date": "2025-08-06"}, # missing name & price
    {"id": 8, "name": "Banana",  "category": "Fruit",     "price": 0.85, "quantity": 20, "city": "Porto",   "date": "2025-08-07"},
]

df = pd.DataFrame(data)
df["date"] = pd.to_datetime(df["date"])

df

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
6   7      None      Fruit    NaN         5     Faro 2025-08-06
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07

In [188]:
# fruit_city = df.copy()
fruit_city.sort_values(by=["price", "quantity"], ascending=[False, True], na_position="last")

   id      name   category  price  quantity     city       date
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
6   7      None      Fruit    NaN         5     Faro 2025-08-06

In [189]:
# 1) Filtering / Subsetting
# Example: Fruits sold in Porto with quantity >= 15
filtered = df[(df["category"] == "Fruit") & (df["city"].eq("Porto")) & (df["quantity"] >= 15)]
filtered

   id    name category  price  quantity   city       date
1   2  Banana    Fruit   0.80        25  Porto 2025-08-02
2   3  Orange    Fruit   1.00        15  Porto 2025-08-03
7   8  Banana    Fruit   0.85        20  Porto 2025-08-07

In [190]:
# Another filter: items priced between 1.0 and 2.2 (inclusive), ignoring NaN
between = df[df["price"].between(1.0, 2.2, inclusive="both")]
between

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit    1.2        10   Lisbon 2025-08-01
2   3    Orange      Fruit    1.0        15    Porto 2025-08-03
4   5  Cucumber  Vegetable    2.1         8  Coimbra 2025-08-05
5   6     Apple      Fruit    1.2        10   Lisbon 2025-08-01

In [191]:
# 2) Sorting / Ordering
# Sort by price descending, then quantity ascending for ties
sorted_df = df.sort_values(by=["price", "quantity"], ascending=[False, True], na_position="last")
sorted_df

   id      name   category  price  quantity     city       date
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
6   7      None      Fruit    NaN         5     Faro 2025-08-06

In [ ]:
# 3) Renaming / Relabeling
renamed = df.rename(columns={"price": "unit_price", "quantity": "qty"})
renamed

   id      name   category  unit_price  qty     city       date
0   1     Apple      Fruit        1.20   10   Lisbon 2025-08-01
1   2    Banana      Fruit        0.80   25    Porto 2025-08-02
2   3    Orange      Fruit        1.00   15    Porto 2025-08-03
3   4    Tomato  Vegetable        2.50   12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable        2.10    8  Coimbra 2025-08-05
5   6     Apple      Fruit        1.20   10   Lisbon 2025-08-01
6   7      None      Fruit         NaN    5     Faro 2025-08-06
7   8    Banana      Fruit        0.85   20    Porto 2025-08-07

In [ ]:
# 4) Selecting Columns
selected = renamed[["id", "name", "unit_price"]]
selected

   id      name  unit_price
0   1     Apple        1.20
1   2    Banana        0.80
2   3    Orange        1.00
3   4    Tomato        2.50
4   5  Cucumber        2.10
5   6     Apple        1.20
6   7      None         NaN
7   8    Banana        0.85

In [ ]:

# 5) Deduplication
# Remove exact duplicate rows
no_dupes_exact = df.drop_duplicates(keep="first")
no_dupes_exact

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
6   7      None      Fruit    NaN         5     Faro 2025-08-06
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07

In [ ]:

# 6) Handling Missing Data
# Flag missing values
flagged = df.assign(
    name_missing=df["name"].isna(),
    price_missing=df["price"].isna()
)
flagged

,id,name,category,price,quantity,city,date,name_missing,price_missing
0,1,Apple,Fruit,1.20,10,Lisbon,2025-08-01,False,False
1,2,Banana,Fruit,0.80,25,Porto,2025-08-02,False,False
2,3,Orange,Fruit,1.00,15,Porto,2025-08-03,False,False
3,4,Tomato,Vegetable,2.50,12,Lisbon,2025-08-04,False,False
4,5,Cucumber,Vegetable,2.10,8,Coimbra,2025-08-05,False,False
5,6,Apple,Fruit,1.20,10,Lisbon,2025-08-01,False,False
6,7,None,Fruit,NaN,5,Faro,2025-08-06,True,True
7,8,Banana,Fruit,0.85,20,Porto,2025-08-07,False,False

In [ ]:
# Impute price with median (only for rows where price is NaN)
median_price = df["price"].median(skipna=True)
imputed = df.copy()
imputed["price"] = imputed["price"].fillna(median_price)
imputed

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
6   7      None      Fruit   1.20         5     Faro 2025-08-06
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07

In [ ]:
# Drop rows where 'name' is missing (common for essential identifiers)
dropped = df.dropna(subset=["name"])
dropped

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07

In [ ]:
# Optional: fill non-critical text fields with a placeholder
filled_names = df.copy()
filled_names["name"] = filled_names["name"].fillna("Unknown")
filled_names

   id      name   category  price  quantity     city       date
0   1     Apple      Fruit   1.20        10   Lisbon 2025-08-01
1   2    Banana      Fruit   0.80        25    Porto 2025-08-02
2   3    Orange      Fruit   1.00        15    Porto 2025-08-03
3   4    Tomato  Vegetable   2.50        12   Lisbon 2025-08-04
4   5  Cucumber  Vegetable   2.10         8  Coimbra 2025-08-05
5   6     Apple      Fruit   1.20        10   Lisbon 2025-08-01
6   7   Unknown      Fruit    NaN         5     Faro 2025-08-06
7   8    Banana      Fruit   0.85        20    Porto 2025-08-07

In [192]:
summary = pd.DataFrame({
    "row_count": [len(df)],
    "total_quantity": [df["quantity"].sum()],
    "avg_price": [df["price"].mean(skipna=True)],
    "min_price": [df["price"].min(skipna=True)],
    "max_price": [df["price"].max(skipna=True)],
})
summary

   row_count  total_quantity  avg_price  min_price  max_price
0          8             105   1.378571        0.8        2.5

# grouping, pivot and crosstab

In [ ]:
# Grouping
import pandas as pd
df = pd.DataFrame({
    "date": pd.to_datetime([
        "2025-01-01","2025-01-01","2025-01-02","2025-01-02","2025-01-02","2025-01-03"
    ]),
    "region": ["N","S","N","S","S","N"],
    "product": ["A","A","B","A","B","A"],
    "units": [10, 5, 8, 7, 3, 4],
    "price": [2.0, 2.5, 3.0, 2.0, 3.5, 2.0],
    "customer": ["c1","c2","c1","c3","c2","c4"]
})
df["revenue"] = df["units"] * df["price"]
df

df.groupby("region", as_index=False)["revenue"].sum().sort_values("revenue", ascending=False)

  region  revenue
0      N     52.0
1      S     37.0

In [ ]:
df.head()

        date region product  units  price customer  revenue
0 2025-01-01      N       A     10    2.0       c1     20.0
1 2025-01-01      S       A      5    2.5       c2     12.5
2 2025-01-02      N       B      8    3.0       c1     24.0
3 2025-01-02      S       A      7    2.0       c3     14.0
4 2025-01-02      S       B      3    3.5       c2     10.5

In [ ]:
# totals by region & product with multiple metrics
summary = (
    df.groupby(["region","product"], as_index=False)
      .agg(
          total_units = ("units", "sum"),
          avg_price   = ("price", "mean"),
          orders      = ("product", "count"),
          customers   = ("customer", "nunique"),
          revenue     = ("revenue", "sum")
      )
      .sort_values(["region","revenue"], ascending=[True, False])
)
summary

  region product  total_units  avg_price  orders  customers  revenue
0      N       A           14       2.00       2          2     28.0
1      N       B            8       3.00       1          1     24.0
2      S       A           12       2.25       2          2     26.5
3      S       B            3       3.50       1          1     10.5

In [ ]:
def wavg(x, w):
    return (x * w).sum() / w.sum()

wavg_price = (
    df.groupby(["region","product"])
      .apply(lambda g: wavg(g["price"], g["units"]))
      .reset_index(name="wavg_price")
)
wavg_price

/tmp/ipython-input-2513086213.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: wavg(g["price"], g["units"]))

  region product  wavg_price
0      N       A    2.000000
1      N       B    3.000000
2      S       A    2.208333
3      S       B    3.500000

In [ ]:
# size: number of rows per group (ignores NA issues)
df.groupby("region").size().reset_index(name="rows")

# count: non-null count per column
df.groupby("region")[["units","price"]].count().reset_index()

  region  units  price
0      N      3      3
1      S      3      3

In [ ]:
# top product (by revenue) per region
top_prod = (
    df.groupby(["region","product"], as_index=False)["revenue"].sum()
      .sort_values(["region","revenue"], ascending=[True, False])
      .groupby("region").head(1)
)
top_prod

  region product  revenue
0      N       A     28.0
2      S       A     26.5

In [ ]:
# revenue matrix: rows=region, columns=product
pd.pivot_table(
    df, values="revenue", index="region", columns="product", aggfunc="sum", fill_value=0
)

product     A     B
region
N        28.0  24.0
S        26.5  10.5

In [ ]:
# revenue per day
daily = df.groupby("date", as_index=False)["revenue"].sum()

# revenue per month (safe for irregular dates)
monthly = (
    df.assign(month=df["date"].dt.to_period("M").dt.to_timestamp())
      .groupby("month", as_index=False)["revenue"].sum()
)
daily, monthly

(        date  revenue
 0 2025-01-01     32.5
 1 2025-01-02     48.5
 2 2025-01-03      8.0,
        month  revenue
 0 2025-01-01     89.0)

In [ ]:
# Crosstab: count of products per region
pd.crosstab(df["region"], df["product"])

product  A  B
region
N        2  1
S        2  1